### ISSUE TITLE
Disable shuttlecall votes

### ISSUE THREAD

**Issue by Zyzarda** [HippieStation/HippieStationdeprecated2020#11282]
[Title]: # Your feature needs to have a good title. If you want an object added, the object's name would be a good title, and such. Use common sense.

[Implementation]: # toggle its default on config

[Why]: # Nobody votes so very small amounts of people can call a shuttle on a 5 minute timer.

[Resources]: # nothing

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers

**Comment by Manly-Dwarf** [comment]
no
#11224 should not have been merged in its current state, as it needed an update or more sounds.
Otherwise, shuttle call vote was pretty much worthless. An antagonist running around murdering the entire station was always able to get off scott free because the vote sound is just the generic "attention" sound, so AFKs or people alt-tabbing don't pay attention to it. In general, shuttlecall votes need be more distinct.
Also people who spam them (like W27) need to be beaten.

**Comment by ghost** [comment]
yeah we need one or more of these:
* more noticeable vote sound
* minimum amount of yes votes to call shuttle

**Comment by cris5311** [comment]
id say make it, so 1/3 of all players have to yes vote and they have to have majority. And of course a better sound

**Comment by AnthonyJNgo** [comment]
Going to throw another -1 into this, modify the vote doesn't need to be removed.
