### ISSUE TITLE
Upstream merge removed null crates

### ISSUE THREAD

**Issue by sagaty13** [HippieStation/HippieStationdeprecated2020#11807]
pls revert

**Comment by ghost** [comment]
@Manly-Dwarf prevented me from readding them

**Comment by WarRage333** [comment]
wtf big gay @manly-dwarf

**Comment by Manly-Dwarf** [comment]
would not have a problem with re-adding them if they had somewhat more of a caveat
you could get several surplus crates roundstart if you just purchased money briefcases

**Comment by Manly-Dwarf** [comment]
to quote a guy on the /tg/ PR
"Honestly I would prefer we removed/edited the """gimmick""" item under the pretense that it actually has a really strong situational use and edit the loottable (since I set it up to be piss easy but no one has utilized it reee)

It seems like this would be a nonissue if the moneybriefcases didn't exist and the loot wasn't heavily inclined to be major murder tools."

**Comment by Manly-Dwarf** [comment]
will tell amari to go ahead and re-add them though, improve not remove as they say

**Comment by Manly-Dwarf** [comment]
https://github.com/HippieStation/HippieStation/pull/11808
