### ISSUE TITLE
Holoparasite rework: build-a-stand edition

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#11847]
[Title]: Holoparasite rework: build-a-stand edition

[Implementation]: So basically, there's no more "stand types". Instead, each stand has stuff like "major ability", "minor ability", "defense", "offense", "range", et cetera. And you only get X amount of points to put into it total. So you can make the ULTIMATE DEFENSIVE STAND, or "literally just a stand-rush spammer", or "it sets people on fire when it punches them" or whatever. So you could get all sorts of gimmicky stands (or just use a preset that someone will inevitably make and post on the KB discord)

also a stand arrow which just gives you a randomized stand but probably kills you

and also actual stand rushes using `mousedown`

[Resources]: i dunno, someone who knows HTML, maybe? i could probably do this with tgui but dwarf will hate me for it.

thanks to @Manly-Dwarf for the idea

@HippieStation/designers

**Comment by biggiOS** [comment]
:pogchamp: +1

**Comment by Manly-Dwarf** [comment]
add mousedown code and use that for rushes rather than this horrible version we have now where it just plays sound effects and deals damage, PRETENDING that you're punching people really fast when you're not
I want fists flying and crashing into the HoS' face at high speeds, not every other mob ever except it plays the punch sound five times instead of one.

**Comment by lunaman22** [comment]
+1

**Comment by ghost** [comment]
exactly tryna hear that muda muda shit 200x a second

**Comment by AnthonyJNgo** [comment]
You have a PR open for this, all conversation can be moved there.
