### ISSUE TITLE
Extend Round Times

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#11867]
[Title]: Extend Round Times

[Goal]: Allow for rounds to go longer than the current guaranteed 30 minutes.

[Implementation]: Extend vote initiation time to 40 minutes + and a 5 minute voting time (so a 50% round time increase)

[Why]: Currently 100% of rounds end once round vote is allowed. Dead players always vote to restart the round and this coupled with only a 1 minute vote time heavily favors restarts.

[Resources]: None

**Comment by Manly-Dwarf** [comment]
Voting right now sucks as well because there's no sound and not much that really goes by it. Most of the time, the people making the votes are dead antagonists who are mad that they died.
Increasing the time would be okay, especially because it force-calls the shuttle, speeds it up, and does not allow it to be recalled. Kind of annoying watching it be abused.

**Comment by ghost** [comment]
Yeah restart votes gay
+1

**Comment by 88scheming88** [comment]
+1 shuttle call funny but shitty for actual game

**Comment by Manly-Dwarf** [comment]
Pay attention to who the antagonists are, and their ckeys. Watch how much they tend to be the ones who are calling shuttle votes.

**Comment by 88scheming88** [comment]
ngl i call shuttle during cult and gang because its funny

**Comment by ghost** [comment]
@Manly-Dwarf even if it was extended to 5 min and had a noise it would be incredibly "restart sided"

I've thought about other ideas with perhaps requiring a 2/3rds majority or perhaps only allowing alive players to vote but I feel these would end up being heavily one sided as well.

**Comment by Majick1** [comment]
5 minutes might be too long for the vote, I would like to see longer rounds but raising the vote time won't do it, you'll just have people building comm consoles to call the shuttle. Also 30 minutes into a hippie wizard round is too long tbh

**Comment by ghost** [comment]
> 5 minutes might be too long for the vote, I would like to see longer rounds but raising the vote time won't do it, you'll just have people building comm consoles to call the shuttle. Also 30 minutes into a hippie wizard round is too long tbh

Why is 5 min too long? It would make round time 45 min then? Or are you worried about the time needed to initiate another vote?

**Comment by Pyko1** [comment]
I recall being against restart vote when it was introduced.

+1 I ded, pls restart

**Comment by Maroonenahmoron** [comment]
A longer time until voting will mostly help out rounds from being cut off short, however the current interface for shuttle voting won't do...

Give us a message on our HUD on the current votes and make it more visible to encourage **everyone** to vote instead of the people who just happen to be dead and have nothing else to do at the time
