### ISSUE TITLE
Bad cigarette code

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#1699]
In-Game report from higitus:
Revision info: 

Sometimes when you spawn as captain, your hungry jumps up to overfed and there is no way to lower it. While you would thing this is a good thing due to the Rerebase being fat now slows you down.

>Start to get hungry

>Got fat and died

>Spawn as a captain, hasnt happend to any other job

**Comment by Higitus1** [comment]
Alright so I figured out what was causing it. It's not the fact that im the captain but rather the fact the I was smoking the premium Cigar. I gave it to some other guy and he got fat as well. So there is something in that cigar besides nicotine that is causing fatness.

**Comment by cacogen** [comment]
This used to be caused by nicotine having a 10% chance of giving the user between 1 and 10 vitamin on mob life but that's no longer in the code:

https://github.com/HippieStation/HippieStation/blob/master/code/modules/reagents/chemistry/reagents/drug_reagents.dm#L45

_edit:_ 

Actually there are two different copies of the reagent in the code, and I guess cigarettes use the one from the Hippiestation module

https://github.com/HippieStation/HippieStation/blob/master/hippiestation/code/modules/reagents/chemistry/reagents/drug_reagents.dm#L86

**Comment by GuyonBroadway** [comment]
There used to be a check for nutrition in the old code iirc. Ill fix that after work.

**Comment by Carbonhell** [comment]
I don't see anything about vitamin, was it removed? @cacogen

**Comment by tortellinitony** [comment]
yes it was
