### ISSUE TITLE
You cannot insert organs into yourself

### ISSUE THREAD

**Issue by tortellinitony** [HippieStation/HippieStationdeprecated2020#2449]
You will eat the organ and then it cannot be inserted. This needs to be fixed somehow.

**Comment by GuyonBroadway** [comment]
I've done self surgery to insert alien organs into myself a few times, what organ was it in particular you were inserting? What body part did your target?

Because if you forget a surgery step, or are trying to insert an organ into a body part where it does not actually go (and some organs are in odd places) you will take a bite out of it instead of inserting it.

**Comment by Carbonhell** [comment]
I dont like how easy it is to waste a good organ with a single bite smh. Id say to change this or in the worst case add a warning message before eating it, jeez

**Comment by PopNotes** [comment]
Could we at least make it so that organs need to be fried before you can eat them?

**Comment by GuyonBroadway** [comment]
I agree with the easy to bite thing, I once managed to snag a xenomorph egg sag from a meaty ores event and bit it because I fucked up the last surgery step and didn't notice. I just wanted  little Xeno friend to help me out on the nuke ops round.

**Comment by ghost** [comment]
honestly just remove bitten organs not working
eating organs is funny and should be kept in the game, biting an organ once and making it unusable is not fun.

**Comment by KayeArray** [comment]
yeah I hate this, biting organs is really dumb

**Comment by GuyonBroadway** [comment]
It's not REALLY a bug just unintuitive code.

**Comment by GuyonBroadway** [comment]
Its not really a bug
