### ISSUE TITLE
The ingredients box (wildcard)

### ISSUE THREAD

**Issue by firegasher** [HippieStation/HippieStationdeprecated2020#3006]
Joined shift as a chef/cook. in my bag i have an invible box called "The ingredients  box (wildcard) " unable to open it but can pick up and drop it. 

/obj/item/storage/box/ingredients/wildcard

This is the path that jamies said to add to the report

**Comment by TungstenOxide** [comment]
Yeah, I'm getting that bug too.

**Comment by TungstenOxide** [comment]
Hey, I found something. The item is called, "donk_kit"

Donk kit doesn't exist.

**Comment by TungstenOxide** [comment]
I changed it to a normal box and now it's at least visible. If I understand the code correctly, It's supposed to change icons, but I don't think that's happening, so it defaults to "donk_kit" which might be deliberate.

**Comment by TungstenOxide** [comment]
Okay, I'm gonna make a pull request so that Chef is actually playable until I can figure this out. I made a new icon. What I think is happening is that the actual Ingredient Box isn't supposed to exist, and there's supposed to be a unique sprite for each box. I'm gonna have to do some digging, but I think that's what's happening.

**Comment by j-mie** [comment]
Fixed by https://github.com/HippieStation/HippieStation/pull/3088
