### ISSUE TITLE
Implants broken?

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#3228]
In-Game report from nziswat:
Revision info: 

>General description of the issue
Implanters and implants from RND seem to either be broken or not intuitive enough to use.

>What you expected to happen
I'd assume you're supposed to stick in implant into a case and then stick into into an implanter and then implant yourself but no matter what nothing seemed to work at all.

>What actually happened
literally nothing

>Steps to reproduce if possible
get implant
get implanter
get implant case
furiously try to figure out wtf is wrong
give up

**Comment by TrickyDickRichard** [comment]
there's 2 types of implants, an injected implant and an implanted augment. the injected implants will come IN THE CASE when made with the protolathe, while you have to use AUGMENTATION with the medical drapes to implant augmentations. the big difference here: one will look like a case with a green thingy in it and the other will look like a mechanical piece. use the surgery guide on the wiki if you're having trouble implanting augments > https://wiki.hippiestation.com/index.php?title=Surgery
there is no issue here, you should have asked someone in mentorhelp or ahelp before posting an issue.

**Comment by nziswat** [comment]
nice meme, I guess i should have mentioned the fact that I do know the difference, and it should probably be more clear anyway, how about the reviver implant? it says implant in the name, how the fuck do you inject it? alright how about the medical arm? surgery for augmentation doesn't actually work since it's for robolimbs and not "cybernetics". here's 2 things that did work though, thermal eyes which are obviously cybernetic organs since they replace something and the sad trombone implant which was the only implant that came in a case. None of the other implants come in case, and you cant stick them into a case too. you can't stick them directly into an implanter too. by the way, ask someone in ahelp? that's the first thing I did, which fyi, out of 5 admins and 2 mentors no one knew, and the admin who responded to me suggested to me to post this. the issue is either a. this shit doesn't work in the first place anyway. or b. it works in a retarded unobvious way.

**Comment by ghost** [comment]
reviver implant goes into the chest

**Comment by GuyonBroadway** [comment]
And its organ manipulation surgery to insert implants, not augmentation.

**Comment by KayeArray** [comment]
ss13 is unintuitive as fuck nothing new here
