### ISSUE TITLE
Telescience idea

### ISSUE THREAD

**Issue by j-mie** [HippieStation/HippieStationdeprecated2020#3502]
Basically a mirror of Goon telescience

We just need an anti telescience field over vault/armory/the entire of the brig?/caps office?

![image](https://user-images.githubusercontent.com/1857320/30784179-8505bce0-a148-11e7-883c-6947191a791e.png)

**Comment by GuyonBroadway** [comment]
Make "blusepace distortion projectors" basicall machine doodads that block any portals or teleport actions opening in their area.

**Comment by Pyko1** [comment]
not jsut block, make it somehow overload the telesci if it targets bluspace protected areas.

Also should prolly disable it on lavaland, i mean some asshat is going to port in 2 mins to round to open legion gate as its static, not to mention whole gulag cheesing.

Or just make it have an 90% chance of turning you in to a fly if you teleport in to a planetary body due to interference.

**Comment by Pyko1** [comment]
Also I portal is swarmer spawn, i recall.
You will have to change it to something else then.

**Comment by mlgdatboi** [comment]
sure why not

**Comment by Blute1** [comment]
not an issue, just close this

**Comment by PopNotes** [comment]
stuff it in projects or something
