### ISSUE TITLE
Mining issue

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#5234]
In-Game report from multipleshoe:
Server info: 24932 (Hippie Station)

>General description of the issue
When i go to mine a rock it says :you cut into the rock" But nothing happens this is with the majority

>What you expected to happen
It should just cut it

>What actually happened
It wont cut it

>Steps to reproduce if possible

Gulag and cut ore

**Comment by xTrainx** [comment]
i made an issue report about this, but i dont seem to find it, so i will put the information here, Minning tiles with pickaxe type tools (pickaxes, drills, sonic jackhammers) and even exosuit drills wont work on rock walls with ores in them, and some tiles on the floor when digging. This has been happening since about 1 or 2 weeks ago

**Comment by GuyonBroadway** [comment]
fixed alegedly
