### ISSUE TITLE
HOLY FUCKING SHIT 

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#6873]
In-Game report from asskek:
Server info: 26937 (Hippie Station)

>General description of the issue
you can no longer take things out of your ass

>What you expected to happen
you can no longer take things out of your ass

>What actually happened
you can no longer take things out of your ass

>Steps to reproduce if possible
you can no longer take things out of your ass

**Comment by Manly-Dwarf** [comment]
>you can no longer take things out of your ass

**Comment by Carbonhell** [comment]
what the fuck is this real
oh god no

**Comment by praisenarsie** [comment]
feature, new lore, your ass is a bluespace rupture and anything you put in it can't get taken out

**Comment by tortellinitony** [comment]
definitely a line that got deleted in a merge or something

The container should be inside of the mob with the ass, but it probably isn't anymore. That's what would cause this bug

**Comment by ghost** [comment]
FIX THIS POST HASTE

**Comment by JohnGinnane** [comment]
gonna test this and see what the story is

**Comment by JohnGinnane** [comment]
Found the cause. It was the bulk upstream merge which removed the code. Trying to open this link might cause your PC to lag because a lot of files were changes so I took a screenshot for convenience

https://github.com/HippieStation/HippieStation/commit/c58fb1bfc600b72bb52a6c69ffa3a25c39fdbee5#diff-b8ba05227a99d959bdb03d7c6c5c6ea8

![image](https://user-images.githubusercontent.com/3355198/36945322-0eb39b04-1fa4-11e8-9da0-278b4270d6cb.png)
