### ISSUE TITLE
Facehugger Miner Tator Item

### ISSUE THREAD

**Issue by Caxxo1** [HippieStation/HippieStationdeprecated2020#9500]
Bring back the facehugger miner tator item that used to cost 20 tcs.
It was great setting up a base, facehugging yourself and then being a salty bitch in dedchat because someone else got to be the larva

**Comment by MrWankman** [comment]
lol Seems a good mem

**Comment by ghost** [comment]
Not until Xenos get nerfed. Also, this is an item which *completely* changes the round mode; having every miner traitor round be Xenos kind of makes the game unfun as well. -1 if the item is still just a facehugger.

**Comment by MrWankman** [comment]
I mean that's like saying we should nerf singulo if we get people who want to just rush to let loose a giant singulo in engineering for their traitor round.

**Comment by Caxxo1** [comment]
What if aside from 20tcs it were to also require diamonds, uranium and a tad of bluespace ?

**Comment by ghost** [comment]
I mean, that would still be quite easy to get for miners. 10 mins of mining max.
@MrWankman being a traitor isn't an excuse to 'do whatever'. I doubt the admins would look kindly to someone who just used their traitor status to grief massively without doing their objectives. I could possibly see someone using this as a way to get the shuttle called, but it definitely won't be a 'rush'

On the other hand, a traitor will gain nothing (except from 'die a glorious death') from causing an alien infestation. If the ayys are decent, the station will be long gone by the time the shuttle arrives, and that probably includes our traitor man. That is my reasoning behind this.

**Comment by ghost** [comment]
1. Even though it's *allowed*, it's still heavily frowned upon. We shouldn't be adding IMG's (Items of Mass Griefing) without good reason. This is also considering that traitors are *heavily encouraged* to complete their objectives; giving them the option to foresake those objectives and start an alien outbreak is **not** encouragement.

2. 'Players are retarded anyways' should rarely be a reason for implementing features. Would you be in favour of removing The Maxcap because 'players are too retarded to make bombs'? Would you be in support of putting back NTSL because 'players are too retarded to break the code'? Would you want throwing circuits to still do damage because 'players are too retarded to configure it properly'? Not all players are retarded, and the number of those decreases rapidly as they gain experience.

Edit: Even though throwing circuits still do damage, my point still stands. 'Players are retarded' is not a valid counterargument in any situation, and all of the examples demonstrate that quite clearly.

**Comment by BlueNothing** [comment]
Um... throwing circuits *do* still do damage.

**Comment by ghost** [comment]
brotha it's just fun, why not let it be?

**Comment by Maroonenahmoron** [comment]
No way I would agree on the old 20TC for one facehugger, it completely changes the round type.

It would hilarious however... if there was a rabid facehugger that works like the reverse bear trap, except it requires to be thrown at someone’s face to activate.

**Comment by Eagle-Eyess** [comment]
-1 xenos too op right now and as maroon stated it completely changes the round type. its like if a traitor could call a nuke ops on the station for 20 tc

**Comment by Lxtoofonea** [comment]
+1, xenos are fun, not trying to kill them, because they are indeed op, but just trying to contain and survive them.
